import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    host: true,
    port: 5173,
    https: ((): any => {
      try {
        // load self-signed cert if generated by npm run cert
        const fs = require('fs')
        const keyPath = './dev-cert/localhost.key'
        const certPath = './dev-cert/localhost.crt'
        if (fs.existsSync(keyPath) && fs.existsSync(certPath)) {
          return { key: fs.readFileSync(keyPath), cert: fs.readFileSync(certPath) }
        }
      } catch (e) {
        // ignore and fall back to http
      }
      return false
    })()
  }
})
