// Blocks client scaffold (read-only config generated by CLI)
import { createBlocksClient } from '@seliseblocks/client'

export const blocksClient = createBlocksClient({
  apiUrl: 'https://blocksapi.slsblx.com',
  appDomain: 'https://dbjcxu-ejcqg.slsblx.com',
  oidc: {
    clientId: '769edfaf-75d2-462f-8d10-68d44a2c82fc',
    scope: 'openid profile',
    url: 'https://iam.seliseblocks.com'
  },
  xBlocksKey: 'D4e4a58e95710414a9bc8b40fa7d29da2'
})

export default blocksClient
